apiVersion: v1
kind: Service
metadata:
  name: analytics-website-svc
spec:
  type: NodePort
  selector: { app: analytics-website }
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008
